name: Broken
options:
  bundleIdPrefix: ${BUNDLE_ID_PREFIX}
  deploymentTarget:
    iOS: 13.0
targets:
  Broken:
    type: application
    platform: iOS
    sources: 
      - path: Broken
    settings:
      DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    info:
      path: Broken/Resources/Info.plist
      properties:
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: ${BUNDLE_ID_PREFIX}.Broken
        CFBundleVersion: "1.0"
        CFBundleShortVersionString: "1.0"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              -
                UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UILaunchStoryboardName: LaunchScreen
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations: []
    postCompileScripts:
      - script: |
          if [ -z "$CI" ]; then
          ${PODS_ROOT}/SwiftLint/swiftlint --fix
          fi
        name: SwiftlintFix
      - script: |
          if [ -z "$CI" ]; then
          ${PODS_ROOT}/SwiftLint/swiftlint
          fi
        name: Swiftlint
