name: Broken
options:
  bundleIdPrefix: ${BUNDLE_ID_PREFIX}
  deploymentTarget:
    iOS: 13.0
targets:
  Broken:
    type: application
    platform: iOS
    sources: 
      - path: Broken
    settings:
      DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    scheme:
      testTargets:
      - BrokenTests
      - BrokenUITests
    postCompileScripts:
      - script: Pods/Swiftlint/swiftlint --fix
        name: SwiftlintFix
      - script: Pods/Swiftlint/swiftlint
        name: Swiftlint
  BrokenTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BrokenTests
  BrokenUITests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BrokenUITests
