name: Broken
options:
  bundleIdPrefix: heartsker
  deploymentTarget:
    iOS: 13.0
targets:
  Broken:
    type: application
    platform: iOS
    sources: 
      - path: Broken
    settings:
      DEVELOPMENT_TEAM: XHRWYM4T65
    scheme:
      testTargets:
      - BrokenTests
      - BrokenUITests
    postCompileScripts:
      - script: ${PODS_ROOT}/Swiftlint/swiftlint --fix
        name: SwiftlintFix
      - script: ${PODS_ROOT}/Swiftlint/swiftlint
        name: Swiftlint
  BrokenTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BrokenTests
  BrokenUITests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BrokenUITests
